### ISSUE TITLE
Support light/dark themes

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#1]

**Comment by thundron** [comment]
Bootstrap v5.3.0 has built-in support for dark mode [since mid 2023](https://blog.getbootstrap.com/2023/05/30/bootstrap-5-3-0/#dark-mode)

> Bootstrap’s new dark mode is opt-in by default, meaning you’ll need to set a `data-bs-theme` attribute on the root `<html>` element to change the entire page’s design.

There's a number of custom colors that needs to be revised as a result, i.e. code blocks don't really play well with the dark theme as they contain ad-hoc coloring

**Comment by jviotti** [comment]
Thanks for digging into it @thundron . I'll play around with it, hopefully soon.

> There's a number of custom colors that needs to be revised as a result, i.e. code blocks don't really play well with the dark theme as they contain ad-hoc coloring

Yeah, we need to tweak them to use Bootstrap variables instead in all cases, so they accommodate accordingly

**Comment by jviotti** [comment]
Haha it does look quite bad at the moment indeed. I'll be working on getting this up and running soon

![Screenshot 2024-05-16 131840](https://github.com/Intelligence-AI/learnjsonschema.com/assets/2192773/a2a489c6-44e9-4c6b-9898-c368cacff8ea)

**Comment by jviotti** [comment]
Its shaping up!

![Screenshot 2024-05-16 132550](https://github.com/Intelligence-AI/learnjsonschema.com/assets/2192773/8beb4acc-0857-4361-955e-6cb43248f799)

**Comment by jviotti** [comment]
And it's done!

![Screenshot 2024-05-16 153906](https://github.com/Intelligence-AI/learnjsonschema.com/assets/2192773/b3209c7f-e183-4fa9-8b8e-c0f7ae2382c9)
