### ISSUE TITLE
Typo in number enum

### ISSUE THREAD

**Issue by PrincessSparkles** [Intelligence-AI/learnjsonschema.com#123]
https://github.com/intelligence-ai/learnjsonschema.com/blob/main/content/2020-12/validation/enum.markdown

The example number enum is

`[2, 46, 100]`

and you assert that an instance with a value of `45` would match.

I think that a value of `46` would match (or that the enum should be `[2, 45, 100]`)

**Comment by jviotti** [comment]
Thanks for reporting @PrincessSparkles ! @AgniveshChaubey Can you cross check this one?

**Comment by AgniveshChaubey** [comment]
Thanks for reporting @PrincessSparkles! Fixed in #124

**Comment by AgniveshChaubey** [comment]
Closing as it is addressed in #124
