### ISSUE TITLE
{   "$schema": "https://json-schema.org/draft/2020-12/schema",   "$id": "https://example.com/product.schema.json",   "title": "Product",   "description": "A product in the catalog",   "type": "object" }

### ISSUE THREAD

**Issue by mahmod87** [Intelligence-AI/learnjsonschema.com#143]
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Product",
  "description": "A product in the catalog",
  "type": "object"

**Comment by jviotti** [comment]
Can you elaborate more on what the issue is? Please re-open with more info!
