### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#2]

**Comment by Era-cell** [comment]
Hi!! I think if the aim of the search will be to redirect to url just based on the keyword search. 
we can implement it just using Javascript? - simple searching substrings method in JS.

Also I tried algolia search, rn maybe I didn't find it that successful ... so, maybe I need to know the structure of the objects array on which we need to implement algolia search

**Comment by jviotti** [comment]
cc @RonItelman Are you aware of nice services to implement search capabilities on static sites?

**Comment by Era-cell** [comment]
> Whatever works and gives us a good search experience. I saw many similar sites using Algolia, so that's why I suggested that, but maybe there are other options. Definitely worth doing some proper research.
> 
> On the JS approach, that'd work but I think it might be too simple. For example, you could search on the metadata of each keyword but not in the content explanations?

What I can get from this is we may need to store the description data again in JSON files, as algolia search works on JSON files...

**Comment by jviotti** [comment]
I was wondering if there is any search provider service that automatically scans/caches the live pages they would see at learnjsonschema.com to serve for their own search without us doing anything.

**Comment by Era-cell** [comment]
> I was wondering if there is any search provider service that automatically scans/caches the live pages they would see at learnjsonschema.com to serve for their own search without us doing anything.

{noted}

**Comment by jviotti** [comment]
Yeah, I don't know how we could even generate those JSON documents. Probably worth a bit more research

**Comment by jviotti** [comment]
This looks interesting: https://harrycresswell.com/writing/hugo-algolia/

**Comment by jviotti** [comment]
There are also plenty of alternatives that work well with Hugo listed here: https://gohugo.io/tools/search/. Maybe some of them are much easier to work with

**Comment by jviotti** [comment]
This one seems very local and easy: https://makewithhugo.com/add-search-to-a-hugo-site/
