### ISSUE TITLE
Add illustrative examples for each keyword

### ISSUE THREAD

**Issue by Julian** [Intelligence-AI/learnjsonschema.com#35]
I would love to link a user who does not know what say, the `dependentSchemas` keyword does, to the page on dependentSchemas at https://www.learnjsonschema.com/2020-12/applicator/dependentschemas/

But there's really not enough there to comfortably do so.

At very least someone new likely needs to see a worked example or two of the keyword to be able to internalize what it does.

They really therefore need to get linked https://json-schema.org/understanding-json-schema/reference/conditionals#dependentSchemas

What do you think about adding examples to each keyword's page which try to illustrate (with very little additional prose) what the keywords do?

Happy to help if you think this is a good idea!

**Comment by jviotti** [comment]
Yeah, this has been on my list for quite a while. I promise I'll get into it. If you want to send PRs, that'd also be great :) I.e. I believe you can write anything you want in the Markdown content files (i.e. https://github.com/sourcemeta/learnjsonschema.com/blob/main/content/2020-12/applicator/dependentSchemas.markdown) and it'd get rendered after the summary table.

**Comment by jviotti** [comment]
The only thing I didn't figure out is how to represent a schema along with failing and passing instances. UJS does some pretty checkmark / red cross, but I guess we can start super simple?

**Comment by jviotti** [comment]
@Julian You inspired me to make some progress on this today. I sent a PR that introduces a few Hugo shortcodes to render examples like the following:

<img width="1123" alt="Screenshot 2023-10-23 at 20 24 13" src="https://github.com/sourcemeta/learnjsonschema.com/assets/2192773/3dbb17b4-975a-4d7c-813b-34276a730530">

**Comment by jviotti** [comment]
In case you want to send some docs PRs, check out https://github.com/sourcemeta/learnjsonschema.com/blob/main/content/2020-12/validation/type.markdown for some examples of how to use these short-codes.

**Comment by Julian** [comment]
Wow awesome! Will have a look in the morning, looks nice!

**Comment by jviotti** [comment]
We completed the first pass for 2020-12!
