### ISSUE TITLE
Consider making the sidebar toggleable to *not* break down keywords by vocabulary

### ISSUE THREAD

**Issue by Julian** [Intelligence-AI/learnjsonschema.com#36]
I would love it if the sidebar was *not* broken down by vocabulary and simply listed all keywords in alphabetical order. That'd make it way easier to find a keyword when you know it exists. E.g. just now in ~<1 second I wanted to find both `dependentSchemas` and `dependentRequired`, and could not see why they weren't both there -- they were of course, but one was in one vocabulary and one in another, which took a few additional seconds to realize when simply scanning the page.

The counter to doing away entirely with vocabularies in the sidebar is that finding keywords by "relationship" to others -- which is kind of what vocabularies are trying to model -- then becomes harder.

Perhaps a meaningful way of solving both is to have the sidebar have 2 tabs -- one where keywords are broken down by vocabulary, and one where they're simply listed alphabetically. Or a radio slider which you could toggle from "by vocabulary" to "sorted" or whatever.

You may not be surprised on this opinion of mine :D -- feel free to close this of course if you think it's overboard!

**Comment by jviotti** [comment]
> Perhaps a meaningful way of solving both is to have the sidebar have 2 tabs -- one where keywords are broken down by vocabulary, and one where they're simply listed alphabetically. Or a radio slider which you could toggle from "by vocabulary" to "sorted" or whatever.

I like this tab idea. Adding to my TODO list :)

**Comment by jviotti** [comment]
Maybe some tab buttons at the top that say:

- By vocabulary (what we have now)
- By dialect (all at once as you want them)

**Comment by jviotti** [comment]
Fixed by https://github.com/Intelligence-AI/learnjsonschema.com/pull/254
