### ISSUE TITLE
Document `$ref`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#49]

**Comment by jviotti** [comment]
This one is probably quite simple:

- Show it off referring to an absolute URI within/outside the schema
- Show it off referring to a relative URI within/outside the schema
- Show it off referring to a URI (relative/absolute) + JSON Pointer within/outside the schema
- Show it off referring to a URI (relative/absolute) + anchor within/outside the schema
- Maybe examples of JUST a pointer and JUST an anchor too?

**Comment by jviotti** [comment]
Ah, you can also show off `$ref` with URNs?

**Comment by AgniveshChaubey** [comment]
This task was addresed in #119.
