### ISSUE TITLE
Document `$vocabulary`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#52]

**Comment by jviotti** [comment]
This one is interesting. We could:

- Showcase how this looks like for the default meta-schema
- Explain the idea of required/optional vocabularies
- Explain that the core vocabulary MUST always be set, and as required
- Explain that `$vocabularies` is not transitive. A meta-schema inheriting from another meta-schema doesn't inherit its vocabularies
- Recommend very much for meta-schemas to declare this keyword

**Comment by AgniveshChaubey** [comment]
This task was addressed in #230.
