### ISSUE TITLE
Document `$anchor`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#53]

**Comment by jviotti** [comment]
- Maybe explain how this is analogous to `id` in HTML? I guess most people understand that
- Explain that two equal anchors on the same lexical scope is invalid
- Explain that you can reference an anchor with/without a relative/absolute URI too
- Explain that anchors work with URNs too (I guess? Maybe double check 😅)

**Comment by AgniveshChaubey** [comment]
This task was addressed in #113.
