### ISSUE TITLE
Document `allOf`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#56]

**Comment by jviotti** [comment]
We can showcase 

- `allOf` with one subschema only
- `allOf` with multiple subschemas
- `allOf` with boolean schemas?
- Nested `allOf`?
- How schemas within `allOf` interoperate with keywords that affect their siblings, like `additionalProperties` and `minContains`/`maxContains`

**Comment by AgniveshChaubey** [comment]
This task wad addressed in #152.
