### ISSUE TITLE
Document `anyOf`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#57]

**Comment by jviotti** [comment]
We can showcase 

- `anyOf` with one subschema only
- `anyOf ` with multiple subschemas
- `anyOf ` with boolean schemas?
- Nested `anyOf `?
- How schemas within `anyOf` interoperate with keywords that affect their siblings, like `additionalProperties` and `minContains`/`maxContains`

**Comment by jviotti** [comment]
I guess we should also cover the case where there is more than one subschema that matches in `anyOf`

**Comment by jviotti** [comment]
We can also talk about annotation collection might impact this. For example, if you are running with validation only, a JSON Schema implementation may stop validating `anyOf` when it finds a successful one, where as when collecting annotations it has to evaluate all of them. My book explains it like this:

<img width="669" alt="Screenshot 2024-02-26 at 19 46 43" src="https://github.com/Intelligence-AI/learnjsonschema.com/assets/2192773/eaf0cc65-d883-4f74-b038-48f411f7d1cf">

**Comment by AgniveshChaubey** [comment]
This task was addressed in #153.
