### ISSUE TITLE
Document `oneOf`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#58]

**Comment by jviotti** [comment]
Maybe same recipe as in https://github.com/Intelligence-AI/learnjsonschema.com/issues/57, but showcasing:

- An example where more than one subschema matches 
- Explaining that usually, for performance, you rather do `anyOf`, as otherwise you have to evaluate ALL subschemas to make sure only one matches
- Explain that `oneOf` is like an exclusive OR operation

**Comment by AgniveshChaubey** [comment]
This task was addressed in #154.
