### ISSUE TITLE
Document `not`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#62]

**Comment by jviotti** [comment]
- Explain that `false` schemas, as in `additionalProperties: {}` are typically thought of as an alias to `{ not: {} }`
- For fun, I guess you could cover the `{ not: false }` case? 😅 
- Cover what happens with annotations within negated schemas. As far as I remember they are dropped, but worth checking?

**Comment by AgniveshChaubey** [comment]
This task was addressed in #147.
