### ISSUE TITLE
Document `properties`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#63]

**Comment by jviotti** [comment]
This one is very fundamental but still interesting:

- Explain properties set to just `false`/`true`
- Explain the relationship/interdependence with `patternProperties`/`additionalProperties`
- Explain the annotations this keyword produces, which more people are unaware of
- Maybe explain that if you don't define a property using this keyword or `patternProperties`, but don't disallow it with `additionalProperties`, it would still be valid with whatever value

**Comment by AgniveshChaubey** [comment]
This task was addressed in #133.
