### ISSUE TITLE
Document `additionalProperties`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#64]

**Comment by jviotti** [comment]
This one is very fundamental but still interesting:

- Explain what passing `false` here actually means
- Explain that you can actually pass a full-blown schema here. Most people don't realize that
- Explain the relationship/interdependence with `patternProperties`/`properties`
- Explain the annotations this keyword produces, which more people are unaware of
- Have a note maybe explaining that JSON Schema is a constraint language and if you don't limit keywords like this, then more keywords than what you defined in `properties`, etc would be allowed

**Comment by AgniveshChaubey** [comment]
This task was addressed in #141.
