### ISSUE TITLE
Document `contains`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#70]

**Comment by jviotti** [comment]
- Explain the annotations this keyword produces
- Explain how it relates to `items` and `prefixItems`, as some people seem to be a bit confused by it, mainly with `items`

**Comment by jviotti** [comment]
On the annotation case, we can show off how it can be either a boolean or an integer, showing both cases?

**Comment by AgniveshChaubey** [comment]
This task was addressed in #150.
