### ISSUE TITLE
Document `deprecated`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#77]

**Comment by jviotti** [comment]
We should:

- Highlight that this keyword doesn't affect validation at all. Its just informative
- Simple example of a schema without subschemas that declares it at the top level
- Slightly more complicated example of producing this annotation in conjunction with logical operators. For example, `if`, `then`, `else`, where the annotation is different, explaining how annotations can often not be determined at runtime 
- Another more complicated example of a schema producing the same annotation for the same instance location more than once. For example, a schema declares the annotation, but references another schema that also declares the same annotation 

Clarify that the value of this keyword is use case specific. The application consuming the schema can decide what to do with this information, if any

**Comment by AgniveshChaubey** [comment]
This task was addressed in #161.
