### ISSUE TITLE
Document `contentSchema`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#80]

**Comment by jviotti** [comment]
If the given string type is a binary string (i.e. defined with `contentEncoding`) that represents a JSON document, then this keyword defines the JSON Schema that applies to that resulting document.

- Again, clarify that this is only an annotation and validation is not performed out of the box. Instead, applications are expected to make use of this as they see fit
- Clarify that providing a schema that doesn't match against the resulting JSON document is of course an error

For an example, maybe extend the example I proposed in https://github.com/Intelligence-AI/learnjsonschema.com/issues/81#issuecomment-1927568688 to also include a content schema?

**Comment by AgniveshChaubey** [comment]
This task was addressed in #155.
