### ISSUE TITLE
Document `contentMediaType`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#81]

**Comment by jviotti** [comment]
We should discuss that:

- This keyword is only an annotation and doesn't affect validation
- It is supposed to be media type of the binary string in question AFTER being decoded as specified in `contentEncoding`
- We should clarify that using this keyword WITHOUT `contentEncoding` is probably an error
- Clarify that this keyword MUST be set to a IANA media type as described in https://www.rfc-editor.org/rfc/rfc2046.html
- We can link to the list of all registered IANA media types: https://www.iana.org/assignments/media-types/media-types.xhtml
- Suggest people to not come up with their own IANA media types?

For examples:

- Maybe use `contentEncoding: bas64` and set `contentMediaType: text/json` and show an instance consisting of a stringified JSON document in base 64? 
- Show both `contentEncoding` and `contentMediaType` being collected as annotations

**Comment by AgniveshChaubey** [comment]
This task was addressed in #156.
