### ISSUE TITLE
Document `contentEncoding`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#82]

**Comment by jviotti** [comment]
- This keyword is only an annotation and doesn't affect validation, but that users should not use this keyword to an incorrect value of course (i.e. don't put base64 if the string is not base64). How it is treated is application dependent
- It represents the type of binary encoding of the string under question. 
- We should clarify that the spec doesn't publish a list of the possible encodings, but we recommend following standard names like "base64" from RFC 4648. Tell people to be mindful about this! 

For examples:

- A very simple schema taking a string in base64, and as a passing example, "Hello World" encoded in base64, or something like that
- Show that `contentEncoding` is collected as an annotation

**Comment by jviotti** [comment]
Maybe what we should also do is start a table of "proposed" content encodings, at least to eventually become a source of industry standard encodings. I guess you can start listing base16, base32, and base64 from https://www.rfc-editor.org/info/rfc4648?

**Comment by AgniveshChaubey** [comment]
This task was addressed in #157.
