### ISSUE TITLE
Document `unevaluatedProperties`

### ISSUE THREAD

**Issue by jviotti** [Intelligence-AI/learnjsonschema.com#83]

**Comment by jviotti** [comment]
- Explain what the concept of "evaluation" means in this case and what does it mean for a property to not be evaluated
- Show it off alongside `properties`, `patternProperties`, etc. Mainly, cover how this keyword is defined based on the *annotations* that these keywords produce
- Explain the annotations this keyword produces 
- Show it being a schema and a boolean (both true and false)
- Maybe show its relationship when the corresponding keywords are not directly siblings to it, but within an `allOf` or through a `$ref`?

**Comment by jviotti** [comment]
This one is an important one to nail down well, as 99% of the community out there is VERY confused about this vocabulary

**Comment by AgniveshChaubey** [comment]
This task was addressed in #128.
